### ISSUE TITLE
Make Django models and setup DB to connect to it

### ISSUE THREAD

**Issue by akshgpt7** [akshgpt7/Fship#1]
Set up the db and make the Django models for various components.

**Comment by Ochibobo** [comment]
The #5 has the Neo4J - Django connection implemented with a couple of models (the neo4j_django_rest branch). Instructions on how to setup the projects are in the main-branch's readme.md.

**Comment by Ochibobo** [comment]
This has already been done. #10 contains all required models and the DB is fully setUp. What's left is the choice of where to host the DB.
